PetFinder/Controllers/MascotaController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ImageMagick;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PetFinder.Models;

namespace PetFinder.Controllers
{
    [Authorize(Policy = "Administrador")]
    public class MascotaController : Controller
    {
        private readonly int _RegistrosPorPagina =6;
        private PaginadorGenerico<Mascota> _PaginadorCustomers;
        private List<Mascota> listaMascotas = new List<Mascota>();
        private List<Mascota> misMascotas = new List<Mascota>();
        private readonly DataContext contexto;
        private readonly IConfiguration config;

        public MascotaController(DataContext contexto, IConfiguration config)
        {
            this.contexto = contexto;
            this.config = config;
        }

        // GET: Mascota
        public ActionResult Index(int pagina = 1)
        {
            var user = contexto.Usuarios.FirstOrDefault(u => u.Email == User.Identity.Name);
            int _TotalRegistros = 0;
            using (contexto)
            {
                // Número total de registros de la tabla Mascotas
                _TotalRegistros = contexto.Mascotas.Where(m => m.UsuarioId != user.UsuarioId).Count();

                // Obtenemos la 'página de registros' de la tabla Mascotas
                listaMascotas = contexto.Mascotas.OrderBy(x => x.Fecha)
                                                 .Where(x=>x.UsuarioId!=user.UsuarioId)
                                                 .Skip((pagina - 1) * _RegistrosPorPagina)
                                                 .Take(_RegistrosPorPagina)
                                                 .ToList();
                
                // Número total de páginas de la tabla Mascotas
                var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
                // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
                _PaginadorCustomers = new PaginadorGenerico<Mascota>()
                {
                    RegistrosPorPagina = _RegistrosPorPagina,
                    TotalRegistros = _TotalRegistros,
                    TotalPaginas = _TotalPaginas,
                    PaginaActual = pagina,
                    Resultado = listaMascotas
                };
                // Enviamos a la Vista la 'Clase de paginación'
                return View(_PaginadorCustomers);
            }            
        }

        // GET: Mascota/Details/5
        public ActionResult Details(int id)
        {
            var mascota = contexto.Mascotas
                            .Include(u => u.Lugar)
                            .Include(r => r.Insentivo)
                            .FirstOrDefault(m => m.MascotaId == id);
            var usuario = contexto.Usuarios.FirstOrDefault(x => x.UsuarioId == mascota.UsuarioId);
            
            mascota.Imagen =  mascota.Foto;
            if (usuario.Email == User.Identity.Name)
            {
                ViewBag.op = "MiMascota";
            }
            else
            {
                ViewBag.op = "Index";
                TempData["idmascota"] = mascota.MascotaId;
            }

            return View(mascota);

        }

        // GET: Mascota/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mascota/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mascota mascota)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var recompensa = new Recompensa
                    {
                        Monto = mascota.Insentivo.Monto,
                        Tiempo = mascota.Insentivo.Tiempo,
                        Estado = 1
                    };
                    if (Convert.ToInt32(recompensa.Monto) > 1)
                    {
                        if (recompensa.Estado == 1)
                        {
                            contexto.Recompensas.Add(recompensa);
                            contexto.SaveChanges();
                            mascota.RecompensaId = recompensa.RecompensaId;
                        }
                    }
                    else
                    {
                        mascota.RecompensaId = 1;
                    }

                    var ubicacion = new Ubicacion
                    {
                        Latitud = mascota.Lugar.Latitud,
                        Longitud = mascota.Lugar.Longitud,
                        Zona = mascota.Lugar.Zona
                    };
                    contexto.Ubicaciones.Add(ubicacion);
                    contexto.SaveChanges();
                    mascota.UbicacionId = ubicacion.UbicacionId;

                    /************************Control de Imagen****************************/
                    var image = mascota.ArchivoImagen;
                    var user = contexto.Usuarios.FirstOrDefault(u => u.Email == User.Identity.Name);
                    mascota.UsuarioId = user.UsuarioId;
                    var fileName = ControlaImagen.CambiarNombre();
                    var folder = "wwwroot\\imagenesUsuarios\\"+ user.UsuarioId + "_" + user.Apellido + "\\";
                    if (!Directory.Exists(folder))
                    {
                        Directory.CreateDirectory(folder);
                    }

                    var filePath = Path.Combine(folder, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    using (MagickImage objMagick = new MagickImage(filePath))
                    {
                        objMagick.Resize(300, 0);
                        objMagick.Write(filePath);
                    }

                    mascota.Foto = user.UsuarioId + "_" + user.Apellido + "\\"+fileName;
                    mascota.Imagen = fileName;
                    /************************Fin de Control de Imgen***********************/
                    mascota.Estado = 1;
                    contexto.Mascotas.Add(mascota);
                    contexto.SaveChanges();
                    ViewBag.Mensaje = "Su mascota se cargo con exito!, precione Volver...";
                    ViewBag.Ok = "ok";
                }

                return View();
            }
            catch (Exception e)
            {
                ViewBag.error = e.InnerException;
                return View();
            }
        }

        // GET: Mascota/Delete/5
        public ActionResult Delete(int id)
        {
            var mascota = contexto.Mascotas.FirstOrDefault(m => m.MascotaId == id);
            mascota.Estado = 0;
            contexto.Update(mascota);
            contexto.SaveChanges();
            return RedirectToAction("MiMascota");
        }


        // GET: Mascota/MiMascota/5
        public ActionResult MiMascota()
        {

            var usuario = contexto.Usuarios.FirstOrDefault(x => x.Email == User.Identity.Name);
            var folder = usuario.UsuarioId + "_" + usuario.Apellido;
            var mascotas = contexto.Mascotas
                                .Include(u => u.Lugar)
                                .Include(r => r.Insentivo)
                                .Where(m => m.Estado == 1 && m.UsuarioId == usuario.UsuarioId);
            
            return View(mascotas);
        }
    }
}

PetFinder/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PetFinder.Models;
using System;
using System.Linq;
using System.Text.RegularExpressions;

namespace PetFinder.Controllers
{
    [Authorize(Policy = "Administrador")]
    public class UsuarioController : Controller
    {
        private readonly DataContext contexto;
        private readonly IConfiguration config;

        public UsuarioController(DataContext contexto, IConfiguration config)
        {
            this.contexto = contexto;
            this.config = config;
        }

        /*******************Index de usuario*******************/
        // GET: Usuario
        public ActionResult Index()
        {
            var u = User.Identity.Name;
            var usuario = contexto.Usuarios.Include(x => x.Vive).FirstOrDefault(x => x.Email == u);

            if (TempData.ContainsKey("MensajeData"))
            {
                ViewBag.Mensaje = TempData["MensajeData"].ToString();
            }

            return View(usuario);
        }

        /******************Crea un usuario nuevo****************/
        // GET: Usuario/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Create(Usuario usuario)
        {
            try
            {
                usuario.Estado = 0;
                if (ModelState.IsValid)
                {
                    string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: usuario.Email,
                    salt: System.Text.Encoding.ASCII.GetBytes(config["Salt"]),
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 1000,
                    numBytesRequested: 256 / 8));

                    hashed = CleanInput(hashed);//quita los caracteres especiales de la cadena
                    new Email().ConfirmarCuenta(usuario.Email,hashed);//Envio del mail

                    usuario.Confirma = hashed;
                    string hashedclave = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: usuario.Clave,
                    salt: System.Text.Encoding.ASCII.GetBytes(config["Salt"]),
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 1000,
                    numBytesRequested: 256 / 8));
                    usuario.Clave = hashedclave;

                    contexto.Usuarios.Add(usuario);
                    contexto.SaveChanges();
                    ViewBag.Mensaje = "Se registro con exito!!!, se le envio un mail para confirmar su cuenta. Revice su correo electronico.";
                    ViewBag.ok = "ok";
                    return View();
                }
                return View(ModelState.Values);
            }
            catch (Exception e)
            {
                ViewBag.StackTrace = e.StackTrace;
                ViewBag.Error = e.Message;
                return View();
            }
        }

        /******************Edita el usuario actual*****************/
        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            var user = contexto.Usuarios.SingleOrDefault(x => x.UsuarioId == id);
            return View(user);
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Usuario user)
        {

            try
            {
                var user_old = contexto.Usuarios.AsNoTracking().SingleOrDefault(u => u.UsuarioId == id);
                user.Clave = user_old.Clave;
                if (ModelState.IsValid && user_old != null)
                {
                    user.UsuarioId = id;
                    user.Estado = 1;
                    contexto.Usuarios.Update(user);
                    contexto.SaveChanges();
                    TempData["MensajeData"] = "Los datos se modificaron con exito!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Error = "Error al intentar modificar los datos!";
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                ViewBag.StackTrace = ex.StackTrace;
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Usuario/Edit/5        
        public ActionResult Details(int id)
        {
            try
            {
                if (TempData.ContainsKey("idmascota"))
                {
                    ViewBag.idmascota = TempData["idmascota"].ToString();
                }

                var user = contexto.Usuarios.AsNoTracking().SingleOrDefault(u => u.UsuarioId == id);
                return View(user);
            }
            catch (Exception ex)
            {
                ViewBag.StackTrace = ex.StackTrace;
                ViewBag.Error = "Error no se Puede mostrar este usuario";
                return View();
            }
        }
        
        // GET: Usuario/CambiaClave/5
        public ActionResult CambiaClave(int id)
        {
            return View();
        }

        // POST: Usuario/CambiaClave/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CambiaClave(CambioClave cambioClave)
        {

            try
            {
                var user_old = contexto.Usuarios.AsNoTracking().SingleOrDefault(u => u.Email == User.Identity.Name);

                if (ModelState.IsValid)
                {
                    string hashedOld = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: cambioClave.OldClave,
                        salt: System.Text.Encoding.ASCII.GetBytes(config["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8));

                    if (user_old.Clave == hashedOld)
                    {
                        string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: cambioClave.NewClave,
                        salt: System.Text.Encoding.ASCII.GetBytes(config["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8));

                        user_old.Clave = hashed;
                        contexto.Usuarios.Update(user_old);
                        contexto.SaveChanges();
                        return RedirectToAction("Logout", "Home");
                    }
                    else
                    {
                        ViewBag.ErrorOldClave = "Contraseña incorrecta";
                        return View();
                    }
                }
                else
                {
                    ViewBag.Error = "Error al intentar modificar los datos!";
                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewBag.StackTrace = ex.StackTrace;
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Usuario/CambiaMail
        public ActionResult CambiaMail()
        {
            ViewBag.mail = User.Identity.Name;
            return View();
        }

        // POST: Usuario/CambiaMail/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CambiaMail(CambiarCorreo model)
        {
            if (ModelState.IsValid && model.NewCorreo == model.RepeatCorreo)
            {
                var user = contexto.Usuarios.FirstOrDefault(x => x.Email == model.OldCorreo);
                user.Email = model.NewCorreo;
                contexto.Usuarios.Update(user);
                contexto.SaveChanges();

                return RedirectToAction("Logout", "Home");
            }
            else
            {
                ViewBag.mail = User.Identity.Name;
                return View(model);
            }
        }

        // GET: Usuario/Contacto
        public ActionResult Contacto()
        {
            ViewBag.user = User.Identity.Name;
            return View();
        }

        // POST: Usuario/CambiaMail/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contacto(ContactoViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                var msj = cvm.Correo + ": " + cvm.Mensaje;
                new Email().EnviarCorreo("postmaster@petfinderarg.com", cvm.Asunto, msj);
                ViewBag.exito = "El Correo se envio con exito";
                ViewBag.ok = "ok";
                return View();
            }
            ViewBag.mensaje = "Error al enviar correo";
            return View();
        }

        /******Cambia el estado del usuario cuando este elimine su cuenta******/
        // GET: Usuario/Delete/5
        /* public ActionResult Delete(int id)
         {
             return View();
         }

         // POST: Usuario/Delete/5
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Delete(int id, IFormCollection collection)
         {
             try
             {
                 // TODO: Add delete logic here

                 return RedirectToAction(nameof(Index));
             }
             catch
             {
                 return View();
             }
         }*/

        public string CleanInput(string strIn)
        {
            // Replace invalid characters with empty strings.
            try
            {

PetFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] PetFinderArg</title>

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <!--<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />-->

</head>
<body>
    <header>        
        <div class="container-fluid">
            <div class="row">
                <div class="mr-auto order-last order-sm-0 logo ml-3">
                    <img src="~/icons/pets2.png" alt=""><span> Pet Finder Arg</span>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="ml-4 order-last order-sm-1">
                        <a asp-controller="Usuario" asp-action="Contacto" ><span class="text-light">Contacto&nbsp;&nbsp;</span></a>
                    </div>
                }
            </div>
        </div>
    </header>
    @if (User.Identity.IsAuthenticated)
    {
        <partial name="_CookieConsentPartial" />
        <main class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-3 barra-lateral-izquierda ml-3" id="barra-lateral-izquierda">
                    <nav>
                        <a asp-controller="Home" asp-action="Index"><img src="~/icons/home.png"> Home</a>
                        <a asp-controller="Usuario" asp-action="Index"><img src="~/icons/man.png" /> Perfil</a>
                        <a asp-controller="Mascota" asp-action="MiMascota"><img src="~/icons/pet.png" /> Mis Mascotas</a>
                        <a asp-controller="Mascota" asp-action="Index"><img src="~/icons/search.png" /> Mascotas Perdidas</a>
                        <a asp-controller="Encontrada" asp-action="Index"><img src="~/icons/girl.png" /> Mascotas Encontradas</a>
                        <a asp-controller="Encontrada" asp-action="Create" data-toggle="tooltip" data-placement="top" title="Si encontraste una mascota hace click aca!"><img src="~/icons/dog.png" /> Encontre una Mascota!</a>
                        <a asp-controller="Mascota" asp-action="Create" data-toggle="tooltip" data-placement="top" title="Si se te perdio tu mascota hace click aca!"><img src="~/icons/veterinary.png" /> Cargar Mascota</a>
                        <!--**********Boton Configuracion***********-->
                        <a href="#bloque1" aria-expanded="false" aria-controls="bloque1" data-toggle="collapse"><img src="~/icons/x26-config2.png" /> Configuraci&oacute;n</a>
                        <div class="collapse" id="bloque1">
                            <div class="dropdown-divider"></div>
                            <a asp-controller="Usuario" asp-action="CambiaClave" class="dropdown-item text-danger"><img src="~/icons/password.png" />&nbsp; Cambiar Contrase&ntilde;a &nbsp;</a>
                            <a asp-controller="Usuario" asp-action="CambiaMail" class="dropdown-item text-danger"><img src="~/icons/x26-mail.png" /> &nbsp; Cambiar Correo &nbsp;</a>
                            <div class="dropdown-divider"></div>
                        </div>
                        <!--***Fin Boton Configuracion***-->
                        <a asp-controller="Home" asp-action="Logout"><img src="~/icons/logout.png" /> Cerrar Sesi&oacute;n</a>
                    </nav>
                </div>
                <a href="#" class="fondo-enlace" id="fondo_enlace"></a>
                <div class="col contenido-principal">
                    <div class="publicar">
                        <div class="row">
                            <!---- Fila del boton menu ---->
                            <div class="col">
                                <a href="#" class="btn-menu d-none d-md-none d-flex justify-content-between" id="btn-menu">
                                    <span>Menu</span>
                                    <img src="~/icons/menu-button.png">
                                </a>
                            </div>
                        </div>

                        <div class="row justify-content-center">
                            <div class="col-12">
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    }
    else
    {
        <div class="row">
            <div class="col-12">
                @RenderBody()
            </div>
        </div>
    }
    <footer class="nav fixed-bottom border-top text-muted">
        <div class="container">
            &copy; 2019 - PetFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/jquery-1.11.1.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>